version: "3.2"
services:
  minio:
    image: bitnami/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: VSWDD9DDdUmpHF8h
      MINIO_ROOT_PASSWORD: 9KzvV0tRJ4jWx4d7Jf2wy2oLusH6M3R5
      MINIO_SERVER_HOST: localhost
      MINIO_SCHEME: http
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    networks:
      - mynet

  mc:
    image: minio/mc
    container_name: mc
    network_mode: host
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --api s3v2 minio http://localhost:9000/ VSWDD9DDdUmpHF8h 9KzvV0tRJ4jWx4d7Jf2wy2oLusH6M3R5;
      /usr/bin/mc rm -r --force minio/first-bucket;
      /usr/bin/mc mb -p minio/first-bucket;
      /usr/bin/mc policy set public minio/first-bucket;      
      /usr/bin/mc admin trace minio -a --debug;
      "

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    networks:
      - mynet

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mynet

  backend:
    restart: always
    image: gabrielmancini/api-upload_backend:latest
    # build:
    #   context: ./
    volumes:
      - .:/src
    depends_on:
      - rabbitmq
      - mongodb
      - minio
    environment:
      PORT: 4000
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      MONGO_URL: mongodb://mongodb:27017/mydb
      ACCESS_TOKEN_SECRET: tokenjwtlalalal
      BUCKET_HOST: http://192.168.0.120:9000/
      BUCKET_ENDPOINT: http://minio:9000/
      BUCKET_ACCESS_KEY: VSWDD9DDdUmpHF8h
      BUCKET_SECRET_KEY: 9KzvV0tRJ4jWx4d7Jf2wy2oLusH6M3R5
    ports:
        - 4000:4000
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
# volumes:
#   s3-data:
#     driver: local
